name: Deployment
on:
  push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1

      - name: Publish to WAPM
        uses: wasmerio/wapm-publish@v1
        with:
          token: ${{ secrets.WAPM_TOKEN }}
